---
- hosts: vagrant
  become_method: sudo
  vars:
      user: ubuntu
      home: /home/{{ user }}
      ansible_processor_vcpus: 3

  roles:
      - { role: common, tags: common }
      - { role: webtier, tags: webtier }
      - { role: dbtier, tags: dbtier }
      - { role: certbot, tags: ssl }
      - {
          role: webproject,
          domain: 'prod.api.geowhim.com',
          ssl: 'false',
#          repository: 'git@bitbucket.org:app-for-us/geo-whim-api.git',
#          version: 'dev',
          workspace: '/home/{{ user }}/www/appforus/api.geowhim.com',
          public_html: '{{ workspace }}/web',
#          script: 'cd {{ workspace }} && composer install --no-interaction --no-dev --no-scripts --optimize-autoloader',
          tags: webproject
        }
