---
- hosts: all
  become_method: sudo
  vars:
      user: vagrant
      home: /home/{{ user }}

  roles:
      - { role: common, tags: common }
      - { role: webtier, tags: webtier }
      - { role: dbtier, tags: dbtier }

  tasks:
      - name: Generating web projects ansible playbook
        become: yes
        template: src=projects.yml.j2 dest=/vagrant/provision/.projects.yml
        when: projects is defined
        tags: webproject
